# Generated by Django 5.2 on 2025-05-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sesion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
