# Generated by Django 5.2 on 2025-05-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sesion', '0002_alter_sesion_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sesion',
            new_name='Sesiones',
        ),
    ]
