# Generated by Django 5.2 on 2025-05-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('anios_experiencia', models.IntegerField()),
                ('camara', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
    ]
