# Generated by Django 5.2 on 2025-05-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fotografo', '0002_remove_fotografo_camara_remove_fotografo_ciudad_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotografo',
            new_name='Fotografos',
        ),
    ]
